[tool.poetry]
name = "data-uri-parser"
version = "0.1.11"
readme = "README.md"
license = "MIT"
description = "A Pythonic data uri parser"
homepage = "https://github.com/unmadeworks/data_uri_parser/"
authors = ["Unmade <backend@unmade.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^20.8b1"
isort = "^5.8"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
