[tool.poetry]
name = "data-uri-parser"
version = "0.1.8"
readme = "README.md"
license = "MIT"
description = "A Pythonic data uri parser"
homepage = "https://github.com/unmadeworks/data_uri_parser/"
authors = ["Unmade <backend@unmade.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
isort = "^4.3"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
