version: 2

workflows:
  version: 2

  development-workflow:
    jobs:
      - development

  deployment-workflow:
    jobs:
      - development:
          filters:
            branches:
              only:
                - master

      - deployment:
          requires:
            - development
          filters:
              branches:
                only: master

jobs:
  development:
    docker:
      - image: circleci/python:3.6.8

    steps:
      - checkout
      - run:
          name: Update poetry (circleci has <1.0 poetry by default)
          command: pip install -U --user poetry
      - run:
          name: Update pip (circleci has < 20.3.3 by default)
          command: pip install -U --user pip
      - run:
          name: Install
          command: poetry install
      - run:
         name: Lint
         command: poetry run black --check .
      - run:
         name: Check imports
         command: poetry run isort --check-only -rc .
      - run:
          name: Test
          command: poetry run pytest
      - run:
          name: Check package version
          command: bash .circleci/check_version.sh

  deployment:
      docker:
        - image: circleci/python:3.6.8

      steps:
        - checkout
        - run:
            name: Update poetry (circleci has <1.0 poetry by default)
            command: pip install -U --user poetry
        - run:
            name: Publish
            command: poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

